"""w1 inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 11:58:53.033239
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escola',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('region', sa.Enum('Norte', 'Nordeste', 'Centro-Oeste', 'Sudeste', 'Sul', name='region', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escola'))
    )
    op.create_index(op.f('ix_escola_name_key'), 'escola', ['name_key'], unique=False)
    op.create_table('professor',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN_LOCAL', 'PROFESSOR', name='role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professor')),
    sa.UniqueConstraint('username', name=op.f('uq_professor_username'))
    )
    op.create_table('acesso_admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('read', 'create', 'update', 'delete', 'upload', 'process', name='admin_action', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['professor.id'], name=op.f('fk_acesso_admin_admin_id_professor')),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_acesso_admin_professor_id_professor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acesso_admin'))
    )
    op.create_index(op.f('ix_acesso_admin_professor_id'), 'acesso_admin', ['professor_id'], unique=False)
    op.create_index(op.f('ix_acesso_admin_resource_id'), 'acesso_admin', ['resource_id'], unique=False)
    op.create_table('disciplina',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_disciplina_professor_id_professor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disciplina'))
    )
    op.create_index(op.f('ix_disciplina_professor_id'), 'disciplina', ['professor_id'], unique=False)
    op.create_table('sessao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('acting_as_professor_id', sa.UUID(), nullable=True),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acting_as_professor_id'], ['professor.id'], name=op.f('fk_sessao_acting_as_professor_id_professor')),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_sessao_professor_id_professor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessao')),
    sa.UniqueConstraint('token_sha256', name=op.f('uq_sessao_token_sha256'))
    )
    op.create_index(op.f('ix_sessao_professor_id'), 'sessao', ['professor_id'], unique=False)
    op.create_table('turma',
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('school_year', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name=op.f('fk_turma_escola_id_escola')),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_turma_professor_id_professor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turma'))
    )
    op.create_index(op.f('ix_turma_professor_id'), 'turma', ['professor_id'], unique=False)
    op.create_table('aula',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('disciplina_id', sa.UUID(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AUDIO_IMPORTED', 'AUDIO_VALIDATED', 'PREPROCESSING', 'TRANSCRIBING', 'TRANSCRIBED', 'DIARIZING', 'READY_FOR_SPEAKER_REVIEW', 'READY_FOR_TRANSCRIPT_REVIEW', 'READY_FOR_FIAS', 'FIAS_COMPLETED', 'WAITING_QTI', 'QTI_COMPLETED', 'TRIANGULATED', 'MTSS_INTERPRETED', 'REPORT_READY', 'ERROR', name='aula_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], name=op.f('fk_aula_disciplina_id_disciplina')),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_aula_professor_id_professor')),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_aula_turma_id_turma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aula'))
    )
    op.create_index(op.f('ix_aula_professor_id'), 'aula', ['professor_id'], unique=False)
    op.create_table('audio',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('internal_filename', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.Enum('audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/mp4', 'audio/aac', 'audio/flac', 'audio/x-flac', name='mime_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('derived_from_audio_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_audio_aula_id_aula')),
    sa.ForeignKeyConstraint(['derived_from_audio_id'], ['audio.id'], name=op.f('fk_audio_derived_from_audio_id_audio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio'))
    )
    op.create_index(op.f('ix_audio_aula_id'), 'audio', ['aula_id'], unique=False)
    op.create_table('audio_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('internal_filename', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_audio_upload_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_upload')),
    sa.UniqueConstraint('aula_id', name=op.f('uq_audio_upload_aula_id'))
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_job_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index(op.f('ix_job_aula_id'), 'job', ['aula_id'], unique=False)
    op.create_index('ix_job_status_created', 'job', ['status', 'created_at'], unique=False)
    op.create_table('processamento',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('rules_version', sa.String(), nullable=False),
    sa.Column('asr_model', sa.String(), nullable=False),
    sa.Column('asr_model_hash', sa.String(length=64), nullable=False),
    sa.Column('diarization_model', sa.String(), nullable=False),
    sa.Column('fias_model', sa.String(), nullable=False),
    sa.Column('fias_model_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hardware', sa.String(length=200), nullable=False),
    sa.Column('device', sa.String(length=200), nullable=False),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=False),
    sa.Column('transcript_source', sa.Enum('ASR_ORIGINAL', 'TRANSCRICAO_REVISADA', name='transcript_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('stage_times_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AUDIO_IMPORTED', 'AUDIO_VALIDATED', 'PREPROCESSING', 'TRANSCRIBING', 'TRANSCRIBED', 'DIARIZING', 'READY_FOR_SPEAKER_REVIEW', 'READY_FOR_TRANSCRIPT_REVIEW', 'READY_FOR_FIAS', 'FIAS_COMPLETED', 'WAITING_QTI', 'QTI_COMPLETED', 'TRIANGULATED', 'MTSS_INTERPRETED', 'REPORT_READY', 'ERROR', name='processamento_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('role_divergence_rate', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_processamento_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processamento'))
    )
    op.create_index(op.f('ix_processamento_aula_id'), 'processamento', ['aula_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processamento_aula_id'), table_name='processamento')
    op.drop_table('processamento')
    op.drop_index('ix_job_status_created', table_name='job')
    op.drop_index(op.f('ix_job_aula_id'), table_name='job')
    op.drop_table('job')
    op.drop_table('audio_upload')
    op.drop_index(op.f('ix_audio_aula_id'), table_name='audio')
    op.drop_table('audio')
    op.drop_index(op.f('ix_aula_professor_id'), table_name='aula')
    op.drop_table('aula')
    op.drop_index(op.f('ix_turma_professor_id'), table_name='turma')
    op.drop_table('turma')
    op.drop_index(op.f('ix_sessao_professor_id'), table_name='sessao')
    op.drop_table('sessao')
    op.drop_index(op.f('ix_disciplina_professor_id'), table_name='disciplina')
    op.drop_table('disciplina')
    op.drop_index(op.f('ix_acesso_admin_resource_id'), table_name='acesso_admin')
    op.drop_index(op.f('ix_acesso_admin_professor_id'), table_name='acesso_admin')
    op.drop_table('acesso_admin')
    op.drop_table('professor')
    op.drop_index(op.f('ix_escola_name_key'), table_name='escola')
    op.drop_table('escola')
    # ### end Alembic commands ###
