"""w2 pipeline

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22 22:32:28.534548
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo_ia',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('format', sa.Enum('safetensors', 'onnx', 'ggml', 'other', name='modelo_format', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelo_ia'))
    )
    op.create_table('indicador_fias',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('reason', sa.Enum('insufficient_data', name='indicador_reason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('numerator_count', sa.Integer(), nullable=False),
    sa.Column('denominator_count', sa.Integer(), nullable=False),
    sa.Column('n_intervals', sa.Integer(), nullable=False),
    sa.Column('rules_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.Enum('validated', 'PENDING_SCIENTIFIC_VALIDATION', 'engineering_decision', 'draft_pending_researcher_review', name='indicador_validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_indicador_fias_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicador_fias'))
    )
    op.create_index(op.f('ix_indicador_fias_aula_id'), 'indicador_fias', ['aula_id'], unique=False)
    op.create_table('transcricao',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('audio_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('pt-BR', name='transcricao_language', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('asr_model_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.id'], name=op.f('fk_transcricao_audio_id_audio')),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_transcricao_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcricao'))
    )
    op.create_index(op.f('ix_transcricao_aula_id'), 'transcricao', ['aula_id'], unique=False)
    op.create_table('falante',
    sa.Column('transcricao_id', sa.UUID(), nullable=False),
    sa.Column('diarization_label', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('PROFESSOR', 'ALUNO', 'UNASSIGNED', name='falante_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['transcricao_id'], ['transcricao.id'], name=op.f('fk_falante_transcricao_id_transcricao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_falante'))
    )
    op.create_index(op.f('ix_falante_transcricao_id'), 'falante', ['transcricao_id'], unique=False)
    op.create_table('segmento',
    sa.Column('transcricao_id', sa.UUID(), nullable=False),
    sa.Column('falante_id', sa.UUID(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('texto_original_asr', sa.String(length=10000), nullable=False),
    sa.Column('texto_revisado', sa.String(length=10000), nullable=True),
    sa.Column('revisado', sa.Boolean(), nullable=False),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('text_pseudonymized', sa.String(length=10000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['falante_id'], ['falante.id'], name=op.f('fk_segmento_falante_id_falante')),
    sa.ForeignKeyConstraint(['transcricao_id'], ['transcricao.id'], name=op.f('fk_segmento_transcricao_id_transcricao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segmento'))
    )
    op.create_index(op.f('ix_segmento_transcricao_id'), 'segmento', ['transcricao_id'], unique=False)
    op.create_table('classificacao_fias',
    sa.Column('segmento_id', sa.UUID(), nullable=False),
    sa.Column('transcript_source', sa.Enum('ASR_ORIGINAL', 'TRANSCRICAO_REVISADA', name='classificacao_transcript_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('pred_raw', sa.Integer(), nullable=False),
    sa.Column('pred_role_constrained', sa.Integer(), nullable=False),
    sa.Column('confidence_raw', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('rules_version', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmento.id'], name=op.f('fk_classificacao_fias_segmento_id_segmento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classificacao_fias'))
    )
    op.create_index(op.f('ix_classificacao_fias_segmento_id'), 'classificacao_fias', ['segmento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classificacao_fias_segmento_id'), table_name='classificacao_fias')
    op.drop_table('classificacao_fias')
    op.drop_index(op.f('ix_segmento_transcricao_id'), table_name='segmento')
    op.drop_table('segmento')
    op.drop_index(op.f('ix_falante_transcricao_id'), table_name='falante')
    op.drop_table('falante')
    op.drop_index(op.f('ix_transcricao_aula_id'), table_name='transcricao')
    op.drop_table('transcricao')
    op.drop_index(op.f('ix_indicador_fias_aula_id'), table_name='indicador_fias')
    op.drop_table('indicador_fias')
    op.drop_table('modelo_ia')
    # ### end Alembic commands ###
