"""ciclo

A sequência declarada de aulas de uma turma: sem o número previsto, não há
como saber qual aula é a primeira e qual é a última do acompanhamento.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24
"""
from alembic import op
import sqlalchemy as sa

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclo',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('disciplina_id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('n_aulas_previstas', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sa.Date(), nullable=False),
    sa.Column('encerrado_em', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], name=op.f('fk_ciclo_disciplina_id_disciplina')),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_ciclo_professor_id_professor')),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_ciclo_turma_id_turma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ciclo'))
    )
    op.create_index(op.f('ix_ciclo_professor_id'), 'ciclo', ['professor_id'], unique=False)
    op.create_index(op.f('ix_ciclo_turma_id'), 'ciclo', ['turma_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ciclo_turma_id'), table_name='ciclo')
    op.drop_index(op.f('ix_ciclo_professor_id'), table_name='ciclo')
    op.drop_table('ciclo')
    # ### end Alembic commands ###
