"""qti

As tabelas da percepção do estudante sobre o professor, coletada pelo
questionário de 24 itens. resposta_qti não tem nenhuma coluna de identidade:
o respondente é só um índice sequencial dentro da coleta (§48 aplicado às
respostas, não só à voz).

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coleta_qti',
    sa.Column('ciclo_id', sa.UUID(), nullable=False),
    sa.Column('coletado_em', sa.Date(), nullable=False),
    sa.Column('origem', sa.Enum('COLETA_NATIVA', 'IMPORTACAO_EXTERNA', name='origem_qti', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.Column('qti_config_version', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclo.id'], name=op.f('fk_coleta_qti_ciclo_id_ciclo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coleta_qti'))
    )
    op.create_index(op.f('ix_coleta_qti_ciclo_id'), 'coleta_qti', ['ciclo_id'], unique=False)
    op.create_table('resposta_qti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('coleta_id', sa.UUID(), nullable=False),
    sa.Column('response_index', sa.Integer(), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coleta_qti.id'], name=op.f('fk_resposta_qti_coleta_id_coleta_qti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resposta_qti'))
    )
    op.create_index(op.f('ix_resposta_qti_coleta_id'), 'resposta_qti', ['coleta_id'], unique=False)
    op.create_table('resultado_qti',
    sa.Column('coleta_id', sa.UUID(), nullable=False),
    sa.Column('octantes', sa.JSON(), nullable=False),
    sa.Column('agency', sa.Float(), nullable=False),
    sa.Column('communion', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coleta_qti.id'], name=op.f('fk_resultado_qti_coleta_id_coleta_qti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resultado_qti'))
    )
    op.create_index(op.f('ix_resultado_qti_coleta_id'), 'resultado_qti', ['coleta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultado_qti_coleta_id'), table_name='resultado_qti')
    op.drop_table('resultado_qti')
    op.drop_index(op.f('ix_resposta_qti_coleta_id'), table_name='resposta_qti')
    op.drop_table('resposta_qti')
    op.drop_index(op.f('ix_coleta_qti_ciclo_id'), table_name='coleta_qti')
    op.drop_table('coleta_qti')
    # ### end Alembic commands ###
