"""qti_cabecalho

Registra a linha de cabeçalho exata recebida em cada importação externa do
QTI. O avalie-seu-professor não declara versão de formato no que exporta
(ver app/qti/service.py); esta coluna é o substituto honesto disponível sem
alterar aquele sistema — torna duas coletas de formatos diferentes
distinguíveis depois, mesmo sem a importação recusar nenhuma delas.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coleta_qti', sa.Column('cabecalho_recebido', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coleta_qti', 'cabecalho_recebido')
    # ### end Alembic commands ###
