"""triangulacao

Um par (evidência do FIAS, percepção do QTI) por aula, para cada linha de
`pedagogical_rules.triangulation_pairs`. Toda coluna vem do que
`fias_ed_engine.triangulation.triangulate` devolve — nenhuma é calculada
aqui. Conferido contra o diff gerado por autogenerate: nenhuma outra tabela
aparece nele (a armadilha da Task 5).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-24
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triangulacao',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('pair_id', sa.String(), nullable=False),
    sa.Column('fias_kind', sa.Enum('index', 'categories', name='triangulacao_fias_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('fias_ref', sa.JSON(), nullable=False),
    sa.Column('fias_value', sa.Float(), nullable=True),
    sa.Column('qti_available', sa.Boolean(), nullable=False),
    sa.Column('qti_values', sa.JSON(), nullable=False),
    sa.Column('reflection_question', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('validation_status', sa.Enum('validated', 'PENDING_SCIENTIFIC_VALIDATION', 'engineering_decision', 'draft_pending_researcher_review', name='triangulacao_validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_triangulacao_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triangulacao'))
    )
    op.create_index(op.f('ix_triangulacao_aula_id'), 'triangulacao', ['aula_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triangulacao_aula_id'), table_name='triangulacao')
    op.drop_table('triangulacao')
    # ### end Alembic commands ###
