"""mtss

Uma linha por regra do MTSS Tier 1 disparada, já qualificada pelo QTI
(`interpretacao_mtss`), e uma linha por recomendação pedagógica disparada
(`recomendacao_mtss`). Toda coluna vem do que `fias_ed_engine.mtss.evaluate`/
`qualify`/`recommendations` devolve — nenhuma é calculada aqui. Conferido
contra o diff gerado por autogenerate: nenhuma outra tabela aparece nele (a
armadilha da Task 5).

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpretacao_mtss',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('tier1_dimension', sa.String(), nullable=False),
    sa.Column('framing', sa.String(), nullable=False),
    sa.Column('interpretation', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('evidence_segment_categories', sa.JSON(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('validation_status', sa.Enum('validated', 'PENDING_SCIENTIFIC_VALIDATION', 'engineering_decision', 'draft_pending_researcher_review', name='interpretacao_mtss_validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('rules_version', sa.String(), nullable=False),
    sa.Column('qti_agreement', sa.Enum('agree', 'disagree', 'inconclusive', 'unpaired', 'no_qti', name='interpretacao_mtss_qti_agreement', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('qti_evidence', sa.JSON(), nullable=True),
    sa.Column('divergence_question', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_interpretacao_mtss_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interpretacao_mtss'))
    )
    op.create_index(op.f('ix_interpretacao_mtss_aula_id'), 'interpretacao_mtss', ['aula_id'], unique=False)
    op.create_table('recomendacao_mtss',
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('validation_status', sa.Enum('validated', 'PENDING_SCIENTIFIC_VALIDATION', 'engineering_decision', 'draft_pending_researcher_review', name='recomendacao_mtss_validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('qti_agreement', sa.Enum('agree', 'disagree', 'inconclusive', 'unpaired', 'no_qti', name='recomendacao_mtss_qti_agreement', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name=op.f('fk_recomendacao_mtss_aula_id_aula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recomendacao_mtss'))
    )
    op.create_index(op.f('ix_recomendacao_mtss_aula_id'), 'recomendacao_mtss', ['aula_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recomendacao_mtss_aula_id'), table_name='recomendacao_mtss')
    op.drop_table('recomendacao_mtss')
    op.drop_index(op.f('ix_interpretacao_mtss_aula_id'), table_name='interpretacao_mtss')
    op.drop_table('interpretacao_mtss')
    # ### end Alembic commands ###
