"""coleta nativa

O link e o registro de consentimento da coleta nativa do QTI (`link_qti`,
`consentimento_qti`). Nenhuma das duas tabelas carrega identidade de
respondente: `link_qti` guarda o hash do token, nunca o token, e
`consentimento_qti` é uma linha por COLETA (não por estudante), com
`aceites` como contador — nunca um carimbo de tempo por aceite, que seria
um canal de correlação temporal com `resposta_qti` (ordenar as duas tabelas
por tempo e parear vizinhos reconstruiria o vínculo que o §7 proíbe).
`consentimento_qti.coleta_id` é `unique=True`: "uma linha por coleta" é
garantia de banco, não de boa vontade de quem chamar — sem essa restrição,
duas respostas chegando ao mesmo tempo poderiam criar duas linhas de
consentimento via busca-ou-cria em paralelo, reabrindo estrutura por evento.
Nenhuma das duas tabelas tem `device_id`: embora `link_qti` seja artefato do
professor autenticado (onde a coluna seria honesta), uniformizamos com
`consentimento_qti` e `resposta_qti` — que precisam da ausência por serem
tocadas pelo estudante — para que "nas três tabelas da coleta nativa não
existe device_id" seja uma frase verificável em segundos, em vez de uma
exceção por tabela. A procedência de `link_qti` já está na cadeia (coleta →
ciclo → professor). A forma das três tabelas é travada por lista de colunas
permitidas em test_coleta_nativa_modelo.py (não por lista de proibidas), e a
unicidade de coleta_id é travada por um teste que insere duas linhas e
espera IntegrityError. Conferido contra o diff gerado por autogenerate:
nenhuma outra tabela aparece nele.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-26
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentimento_qti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('coleta_id', sa.UUID(), nullable=False),
    sa.Column('documento_versao', sa.String(length=32), nullable=False),
    sa.Column('aceites', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coleta_qti.id'], name=op.f('fk_consentimento_qti_coleta_id_coleta_qti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consentimento_qti')),
    sa.UniqueConstraint('coleta_id', name=op.f('uq_consentimento_qti_coleta_id'))
    )
    op.create_table('link_qti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL_ONLY', 'PENDING_SYNC', 'SYNCED', 'CONFLICT', name='sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('coleta_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('limite_respostas', sa.Integer(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coleta_id'], ['coleta_qti.id'], name=op.f('fk_link_qti_coleta_id_coleta_qti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_qti')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_link_qti_token_hash'))
    )
    op.create_index(op.f('ix_link_qti_coleta_id'), 'link_qti', ['coleta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_qti_coleta_id'), table_name='link_qti')
    op.drop_table('link_qti')
    op.drop_table('consentimento_qti')
    # ### end Alembic commands ###
